name: Publish Package
on:
  # release:
  #   types:
  #     - published
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - use: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing packages
      run: npm ci
    - name: Running linter
      run: npm run lint