name: Publish Package
on:
  # release:
  #   types:
  #     - published
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing packages
      run: npm ci
    - name: Running linter
      run: npm run lint
  publish-package:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
    - name: Installing packages
      run: npm ci
    - name: Publishing Package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

